export const SAVE_TODOS = 'TODO/SAVE_TODOS';
export const DELETE_ONE_TODO = 'TODO/DELETE_ONE_TODO';
export const COMPLETE_ONE_TODO = 'TODO/COMPLETE_ONE_TODO';
export const UPDATE_ONE_TODO = 'TODO/UPDATE_ONE_TODO';
export const PENDING_ONE_TODO = 'TODO/PENDING_ONE_TODO';
export const LOAD_ALL_DATA = 'TODO/LOAD_ALL_DATA';